name: codspeed-benchmarks

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: linux-amd64-gpu-p100-latest-1
    container:
      image: nvcr.io/nvidia/pytorch:23.09-py3
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
      options: --shm-size=1G
      credentials:
        username: $oauthtoken
        password: ${{ secrets.NGC_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements/dev.txt

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests/ --codspeed
