name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  lfs-warning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ppremk/lfs-warning@v3.2
        with:
          filesizelimit: 5MB
